name: Publish package to npm
on: 
  pull_request:
    paths:
      - "ava.test/**"
      - "index.ts"
      - "README.md"
      - ".github/workflows/publish.yml"
      - "package.json"
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"
jobs:  
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 16
          - 14
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - name: Test ✅
        run: npm run test
        env:
          LOCATION: ${{ secrets.LOCATION }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          SUBSCRIPTION_KEY: ${{ secrets.SUBSCRIPTION_KEY }}
      - uses: actions/upload-artifact@v3
        with:
          name: lib
          path: lib

  publish:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 14
      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
      - uses: actions/download-artifact@v3
        with:
          name: lib
          path: lib
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            ./lib/**
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          create_branch: true
          branch: "changelog-${{ github.run_id }}"
